### ISSUE TITLE
Can't replicate

### ISSUE THREAD

**Issue by rdaniel** [THU-BPM/SelfORE#1]
Hi,
I'm very interested in your paper and want to replicate it before testing it on other kinds of content. However, I can't do so since it is missing some of the code while it awaits factorization. Would it be possible to check in the old code as a different branch so that I could start to work with that? Alternatively, do you have an estimated date for the refactoring to be done and the revised code available?

**Comment by xuminghu** [comment]
Sure, please check the unrefactored version in branch[ unrefactored](https://github.com/THU-BPM/SelfORE/tree/unrefactored).
