### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by wjczf123** [THU-BPM/SelfORE#10]
I am not familiar with open relation extraction. Can you give specific information about data processing?

**Comment by wjczf123** [comment]
For the TRex dataset, should I download json or nif?

**Comment by xuminghu** [comment]
We follow Simon's work and process dataset via [trex_to_ttsv.cpp](https://github.com/THU-BPM/SelfORE/blob/unrefactored/data_preprocess/trex_to_ttsv.cpp) provided by Simon.

**Comment by wjczf123** [comment]
Thank you for your reply. I also have some questions.
This file seems to require some parameters? Can you tell me the specific instructions? 
Can this file also be used to process the NYT-FB dataset?

**Comment by xuminghu** [comment]
This file could process TReX directly.
Regarding the NYT-FB data set, the original dataset has been processed. Please contact [dietma](https://github.com/diegma/relation-autoencoder) to obtain it.
