### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by h-peng17** [THU-BPM/SelfORE#2]
How can i get train, dev, test data from raw text data? I want run the code but there was no dataset. Thank you.

**Comment by xuminghu** [comment]
Hello! If you have urgent tasks, please refer to the unrefactored branch, we have provided the data_ preprocess code and dataset download link. We do not have ownership of the NYT + FB data set, please contact [dietma](https://github.com/diegma/relation-autoencoder) to obtain it.
