### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by h-peng17** [THU-BPM/SelfORE#3]
The model always exceeds gpu memory even i set batch_size to 1. So I wonder what's the size of your gpu? Thank you

**Comment by xuminghu** [comment]
Our GPU machine has a total of 7 TITAN RTX (24G each), the SelfORE code needs a similar amount of resources to be run.

**Comment by h-peng17** [comment]
Thank you!

**Comment by angelotran05** [comment]
Sorry for disturbing you. I understand that your SelfORE code can run on multiple GPUs at the same time through the command: CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 python run.py 
Is it right?
