### ISSUE TITLE
How to get sentence_train.json, sentence_train_label.json and sentence_index.json?

### ISSUE THREAD

**Issue by BobXWu** [THU-BPM/SelfORE#4]
Hi, can you show how to get these json files from the data-sample.txt?

**Comment by stronglily** [comment]
hello？Have you got these documents？

**Comment by stronglily** [comment]
> Hi, can you show how to get these json files from the data-sample.txt?

hello？Have you got these documents？

**Comment by xuminghu** [comment]
Thanks for your interest in our work. We have refactored the code and no longer need sentence_index.json. Among them, sentence_train.json represents the training data, sentence_train_label.json represents the gold label corresponding to the training data, which is only used for the evaluation of the final result.
