### ISSUE TITLE
Any news for refactoring?

### ISSUE THREAD

**Issue by bpiwowar** [THU-BPM/SelfORE#5]
Hi, 

we are trying to use your old code, but cannot replicate your results so far - we have trouble in particular with the DEC clustering phase (the algorithm converges with one cluster when KL is minimized). 

In particular, could you tell which (if any) among the two lines is the correct one (and for which dataset):

https://github.com/THU-BPM/SelfORE/blob/6fc1df1b423ed52680226114198cc45a954153e3/adaptive_clustering.py#L218-L219

And is the number of training epochs (default 200) correct?

BTW, when are you planning to release the refactored code? 

Thanks
Benjamin

**Comment by xuminghu** [comment]
Thanks for your interest in our work, we have refactored the code =)
